[project]
name = "xspin"
version = "0.1.0"
description = "Python module for creating terminal spinners."
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
